-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOZ/iaAKFvdj7KZZU
oJQrHv3bUEAIBdNmyxy721DqN4yhRANCAATkDuMixn6LS/ejNr1XrcDWF5gXdEW8
a+EMh3YfUtZLS2s2DaOEkZyK+kRoETKUcWbftz/xPn1+Yq2TNXgNJyJu
-----END PRIVATE KEY-----
